name:Deploy Website CI/CD

on:
push:
branches:
main

jobs:
deploy:
runs-on:ubuntu-latest

steps:
name:Checkout Repository
uses:actions/checkout@v4

name:Setup SSH
run:
mkdir -p ~/.ssh
echo"${{secrets.SSH_PRIVATE_KEY}}">~/.ssh/tes_server_polindra
chmod 600 ~/.ssh/tes_server_polindra
ssH-keyscan-p8022-H${{secrets.SERVER IP }}>>~/.ssh/know_hosts

name:Deploy to Server
run:
rsync -avz --delete\
-e"ssh
-p8022-i~/.ssh/tes_server_polindra"

${{ secrets.SERVER USER }@${{ secrets.SERVER IP }}:${{ secrets.DEPLOY_PATH }}
